# Generated by Django 3.0.3 on 2020-03-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=10)),
                ('Message', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
