# Generated by Django 3.0.3 on 2020-03-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200324_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
