# Generated by Django 3.0.3 on 2020-03-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='images',
            field=models.ImageField(upload_to='login/static/image/'),
        ),
    ]
